-- CreateTable
CREATE TABLE "Enquete" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "pergunta" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Opcao" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "texto" TEXT NOT NULL,
    "votos" INTEGER NOT NULL DEFAULT 0,
    "enqueteId" INTEGER NOT NULL,
    CONSTRAINT "Opcao_enqueteId_fkey" FOREIGN KEY ("enqueteId") REFERENCES "Enquete" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
